name: AutoClash
on:
  push:
    paths:
      - '.github/**'
      #- '!docker/**'
  schedule:
    - cron: '* */6 * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VER: "0.3"
      DH: "${{ secrets.DOCKERHUB_USERNAME }}/flexgetqb"
      TZ: Asia/Shanghai
    #timeout-minutes: 10
    steps:
    #- uses: actions/checkout@v3
    - name: NAT类型
      run: |
        pip install pystun3
        which python 
        which python3 
        exit
    - name: 解压
      run: |
        sudo ufw allow 55555,56881 && date
        unzip -P "${{ secrets.ZIPPASSWORD }}" docker/yaml.zip
        unzip -P "${{ secrets.ZIPPASSWORD }}" docker/autoremove.zip
    - run: docker build -t image1 docker/.
    #-
    #  name: Login to DockerHub
    #  uses: docker/login-action@v1 
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
     #   password: ${{ secrets.DOCKERHUB_PASSWORD }}
    #- 
  #    name: Push
  #    run: |
  #        docker tag image1 $DH:$VER
   #       docker push $DH:$VER
  #        docker tag image1 $DH
  #        docker push $DH
      #-e TZ=Asia/Shanghai -p 56881:56881 -p 56881:56881/udp -p 55555:55555 -p 55555:55555/udp \
    - name: Run Docker
      run: |
        PWD=`pwd`
        docker run -itd --privileged --restart=always --name qb \
        -e WEBUI_PORT=55555  -e UID=1000 -e GID=1000 \
        -e TZ=Asia/Shanghai --net=host \
        -v ${PWD}/config.yml:/root/config.yml \
        -v ${PWD}/autoremove.config.yml:/root/autoremove.config.yml \
        -v ${PWD}/docker/qbapi.py:/root/qbapi.py  \
        image1
        df -h
    - name: START
      run: |
        docker exec qb  ./qbstart.sh
    - name: STOP
      run: |
        docker exec qb python qbapi.py
####
       
