name: AutoClash
on:
  push:
    paths:
      - '.github/**'
      #- '!docker/**'
    #paths-ignore:
      #- 'docker/**'
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VER: "0.1"
      DH: "${{ secrets.DOCKERHUB_USERNAME }}/flexgetqb"
      TZ: Asia/Shanghai
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t image1 docker/.
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - 
      name: Push
      run: |
          docker tag image1 $DH:$VER
          docker push $DH:$VER
          docker tag image1 $DH
          docker push $DH
    - name: 解压
      run: |
        sudo ufw allow 55555 && date
        PWD=`pwd` && echo $PWD
        configYml=$PWD/yaml.zip
        echo configYml
        unzip -nP "${{ secrets.ZIPPASSWORD }}" docker/yaml.zip -d $PWD/yaml.zip
    - name: Docker
      run: |
        docker run -itd --privileged --name qb -e WEBUI_PORT=55555  -e UID=1000 -e GID=1000 -e TZ=Asia/Shanghai -p ::56881 -p ::56881/udp -p 55555:55555 -v ${configYml}:/root/config.yml --restart=always  image1 bash
        run：docker exec qb  flexget -c /root/config.yml --logfile  /root/logs/flexget.log  --test  execute
########
       
